require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'scratch.rb'
    - 'spec/dummy/db/schema.rb'
    - 'vendor/bundle/**/*'

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/dummy/db/schema.rb'

Layout/FirstHashElementIndentation:
  Exclude:
    - 'spec/dummy/config/environments/test.rb'

Layout/LineLength:
  Max: 312

Metrics/AbcSize:
  Max: 89

Metrics/BlockLength:
  Max: 32

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 22

Performance/RegexpMatch:
  Exclude:
    - 'bin/rspec'

Performance/StringInclude:
  Exclude:
    - 'bin/rspec'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20130628143444_user_roles.rb'
    - 'db/migrate/20130628144126_user_institutions.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/concerns/bpluser/omniauth_callbacks.rb'

Rails/ReversibleMigration:
  Exclude:
    - 'db/update_migrate/20230113204303_drop_roles_roles_users_institutions_institutions_users.rb'

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 6

RSpec/NestedGroups:
  Max: 4

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3
