AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Gemspec/OrderedDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/dummy/db/schema.rb'

Layout/LineLength:
  Max: 312

Metrics/AbcSize:
  Max: 89

Metrics/BlockLength:
  Max: 32

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 22

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20130628143444_user_roles.rb'
    - 'db/migrate/20130628144126_user_institutions.rb'

Rails/ReversibleMigration:
  Exclude:
    - 'db/update_migrate/20230113204303_drop_roles_roles_users_institutions_institutions_users.rb'

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/dummy/db/schema.rb'

Style/NumericLiterals:
  Exclude:
    - 'spec/dummy/db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'spec/dummy/db/schema.rb'

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3
