language: ruby
dist: bionic

cache:
  bundler: true
  apt: true

addons:
  postgresql: "12"
  chrome: stable
  apt:
    update: true
    packages:
      - postgresql-12
      - postgresql-client-12

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - gem update --system --no-document
  - gem install bundler:2.3.26 --no-document
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

before_script:
  - RAILS_ENV=test bundle exec rails db:prepare

rvm:
  - 2.7.7

env:
  global:
    - PGVER=12
    - PGHOST=127.0.0.1
    - PGUSER=postgres
    - PGPORT=5432
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - RAILS_VERSION=6.0.6
