language: ruby
dist: jammy

cache:
  bundler: true
  apt: true

addons:
  chrome: stable

services:
  - postgresql

before_install:
  - gem update --system --no-document
  - gem install bundler:2.7.2 --no-document
  - nvm install --lts
  - google-chrome-stable --headless --disable-gpu --disable-software-rasterizer --no-sandbox --remote-debugging-port=9222 http://localhost &

before_script:
  - RAILS_ENV=test bundle exec rails app:db:prepare
  - cd ./spec/dummy && yarn install && yarn build:css && cd ../..

env:
  global:
    - PGHOST=127.0.0.1
    - PGUSER=postgres
    - PGPORT=5432
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - VLR_SITE_ID=commonwealth

matrix:
  include:
    - rvm: 3.4.4
      env: "RAILS_VERSION=7.2.3"
  fast_finish: true
