name: Build branches

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    # strategy:
    #   matrix:
    #     rails_version: ['7.2.3']

    steps:
      - uses: browser-actions/setup-chrome@v2
      - run: chrome --version
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: './spec/internal/yarn.lock'

      # - name: Install packages
      #   run: bundle install

      # - name: Install packages
      #   run: yarn install
      #   working-directory: ./spec/internal